image: "python:3.7"

variables:
  MPLBACKEND: "agg"

docs:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install pandoc
    - git clone https://github.com/SKA-ScienceDataProcessor/rascil rascil
    - cd rascil
    - python setup.py install
    - cd ..
    - pip install -r requirements.txt -r requirements-docs.txt
    - mkdir -p docs/build/html
  script:
    - PYTHONPATH=`pwd`:../rascil make -k -j -C docs html
  after_script:
    - mv docs/build/html html
  artifacts:
    paths:
      - html/
    expire_in: 1 week

unittests:
  stage: build
  before_script:
    - git clone https://github.com/SKA-ScienceDataProcessor/rascil rascil
    - cd rascil
    - python setup.py install
    - cd ..
    - pip install -r requirements.txt -r requirements-test.txt
  script:
    - pip install pytest pytest-xdist pytest-cov
    - PYTHONPATH=`pwd`:../rascil py.test -n 4 tests --verbose --cov=erp --cov-report=html:coverage --forked
  artifacts:
    paths:
      - coverage
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - docs
    - unittests
  script:
    - mv html public
    - mv coverage/ public/coverage
  artifacts:
    paths:
      - public
      - public/coverage
    expire_in: 1 month
  only:
    - master
