image: "python:3.7"

variables:
  MPLBACKEND: "agg"

docs:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install pandoc
    - git clone -b feature_second_eMERLIN https://github.com/SKA-ScienceDataProcessor/rascil
    - cd rascil
    - python setup.py install
    - pip install -r requirements.txt -r requirements-docs.txt
    - cd ..
    - mkdir -p docs/build/html
    - mkdir -p test_results
  script:
    - PYTHONPATH=`pwd` make -k -j -C docs html
  after_script:
    - mv docs/build/html html
  artifacts:
    paths:
      - html/
    expire_in: 1 week

unittests:
  stage: build
  before_script:
    - git clone -b feature_second_eMERLIN https://github.com/SKA-ScienceDataProcessor/rascil
    - cd rascil
    - python setup.py install
    - pip install -r requirements.txt -r requirements-docs.txt
    - cd ..
    - pip install -r requirements.txt -r requirements-test.txt
  script:
    - pip install pytest pytest-cov
    - py.test tests/test*.py --verbose --cov=erp --cov-report=html:coverage
  artifacts:
    paths:
      - coverage
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - docs
    - unittests
  script:
    - mv html public
    - mv coverage/ public/coverage
  artifacts:
    paths:
      - public
      - public/coverage
    expire_in: 1 month
  only:
    - master
