image: "python:3.7"

variables:
  MPLBACKEND: "agg"

docs:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install
    - git clone https://github.com/SKA-ScienceDataProcessor/rascil
    - cd rascil
    - python setup.py install
    - pip install -r requirements.txt -r requirements-docs.txt
    - cd ..
    - git clone https://github.com/timcornwell/eMERLIN_RASCIL_pipeline.git
    - cd eMERLIN_RASCIL_pipeline
    - python setup.py install
    - pip install -r requirements.txt -r requirements-docs.txt
    - mkdir -p docs/build/html
    - cd ..
  script:
    - ERP=`pwd` PYTHONPATH=`pwd`:../erp make -k -j -C docs html
  after_script:
    - mv docs/build/html html
  artifacts:
    paths:
      - html/
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - docs
  script:
    - mv html public
    - mv coverage/ public/coverage
  artifacts:
    paths:
      - public
      - public/coverage
    expire_in: 1 month
  only:
    - master
